POST http://localhost:8787/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "firstName": "Eder",
  "lastName": "Lima",
  "email": "eder@mail.com",
  "password": "password123"
}

###

POST http://localhost:8787/auth/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "eder@mail.com",
  "password": "password123"
}

###

GET http://localhost:8787/auth/profile HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlzcyI6InNoYXJlZmlsZS5hc3luY2hlZC50ZWNoIiwiaWF0IjoiMjAyNC0wMS0xOFQxODoxNToyOS43MTlaIiwiZXhwIjoiMjAyNC0wMS0yNVQxODoxNToyOS43MTlaIn0.Q3-a1yoO8pqSR5TUUul3ATPZb-q7_aorhuQJ_OXEB50
